name: Build and Push to ECR

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::536284936847:role/deeptrain
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        docker build -t your-app-name .
        docker tag your-app-name:latest <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/your-app-name:latest

    - name: Push to ECR
      run: |
        docker push <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/your-app-name:latest
